// Types and invoke functions are generated by tauri-specta (see
// `pnpm run bindings`); this module only keeps the historical names.
import { commands } from "./bindings";
import type { SearchHit, SearchResult, SearchStatus_Serialize } from "./bindings";

export type SkillSearchStatus = SearchStatus_Serialize;
export type { SearchHit };
export type SkillSearchResult = SearchResult;

export const getSkillSearchStatus = () => commands.skillSearchStatus();
export const indexSkillSearch = () => commands.skillSearchIndex();
export const querySkillSearch = (query: string) => commands.skillSearchQuery(query);
export const answerSkillSearch = (query: string, hits: SearchHit[]) =>
  commands.skillSearchAnswer(query, hits);
