// SkillGuideDto is generated by tauri-specta (see `pnpm run bindings`).
// GuideScope is a frontend convenience for the optional scope arguments;
// the wrappers translate it into the explicit nulls the backend expects.
import { commands } from "./bindings";
import type { SkillGuideDto } from "./bindings";

export type SkillGuide = SkillGuideDto;

export interface GuideScope {
  projectId?: string;
  skillRelativePath?: string;
  agent?: string;
}

export const getSkillGuide = (skillId: string, scope: GuideScope = {}) =>
  commands.getSkillGuide(
    skillId,
    scope.projectId ?? null,
    scope.skillRelativePath ?? null,
    scope.agent ?? null,
  );

export const saveSkillGuide = (
  skillId: string,
  content: string,
  reviewedSourceHash?: string,
  scope: GuideScope = {},
) =>
  commands.saveSkillGuide(
    skillId,
    content,
    reviewedSourceHash ?? null,
    scope.projectId ?? null,
    scope.skillRelativePath ?? null,
    scope.agent ?? null,
  );

export const generateSkillGuide = (skillId: string, scope: GuideScope = {}) =>
  commands.generateSkillGuide(
    skillId,
    scope.projectId ?? null,
    scope.skillRelativePath ?? null,
    scope.agent ?? null,
  );
