// Handwritten IPC wrapper layer.
//
// All wire types and the per-command invoke functions are generated by
// tauri-specta into ./bindings (regenerate with `pnpm run bindings`). This
// file only keeps the business semantics the generator cannot know: optional
// arguments collapsing to null, rounded numbers, deprecated aliases, and the
// documented closed string unions that Rust sends as plain `String`.
//
// The `as Promise<…>` casts below narrow generated `string` fields to those
// documented value sets — the same contract the old handwritten interfaces
// asserted implicitly, now visible in one audited place.
/* oxlint-disable typescript/no-unsafe-type-assertion */

import { commands } from "./bindings";
import type {
  GitBackupStatus as GeneratedGitBackupStatus,
  GithubDevicePollResult as GeneratedGithubDevicePollResult,
  MergeSummary as GeneratedMergeSummary,
  ProjectDto,
  ProjectSkillInfo_Serialize,
  SkillInstallItem,
  SkillSourceDiffDto,
  SkillSourceDiffEntryDto,
  SyncOutcome as GeneratedSyncOutcome,
} from "./bindings";

export type {
  AppUpdateInfo,
  BackupSizeReport as GitBackupSizeReport,
  BatchDeleteSkillsResult,
  BatchImportResult,
  BatchUpdateSkillsResult,
  DeviceFlowStart as GithubDeviceFlowStart,
  DiagnosticInfo,
  DiscoveredGroup,
  GitBackupVersion,
  GitPreviewResult,
  GitSkillPreview,
  GithubBackupConnectResult,
  LogExcerpt,
  LogExportResult,
  ManagedSkillDto as ManagedSkill,
  PanicInfo,
  PendingConflictRow as PendingConflict,
  PendingRemoval,
  PresetDto as Preset,
  ProjectAgentTargetDto as ProjectAgentTarget,
  ProjectSkillDocumentDto as ProjectSkillDocument,
  ReimportSkillResult,
  ScanResultDto as ScanResult,
  SkillDocumentDto as SkillDocument,
  SkillInstallItem,
  SkillToolToggleDto as SkillToolToggle,
  SkillsShSkill,
  SourceSkillDocumentDto as SourceSkillDocument,
  SyncHealthDto as SyncHealth,
  TargetDto as SkillTarget,
  ToolCategory,
  ToolInfoDto as ToolInfo,
  UpdateSkillResult,
  UpdatedSkill as MergeUpdatedSkill,
} from "./bindings";

// ── Protocol refinements ──
// Plain `String` on the Rust side, but the backend documents a closed set of
// values. Narrowing here keeps the frontend's exhaustive checks (Record keys,
// state unions) compiling; if the backend gains a value, widen the union.

export type SkillSourceDiffStatus = "added" | "removed" | "modified";
export type SkillSourceDiffContentKind =
  | "text"
  | "binary"
  | "too_large"
  | "permission_only";

export type SkillSourceDiffEntry = Omit<
  SkillSourceDiffEntryDto,
  "status" | "content_kind"
> & {
  status: SkillSourceDiffStatus;
  content_kind: SkillSourceDiffContentKind;
};

export type SkillSourceDiff = Omit<SkillSourceDiffDto, "entries"> & {
  entries: SkillSourceDiffEntry[];
};

export type GitUpstreamHealth =
  | "healthy"
  | "no_remote"
  | "no_upstream"
  | "unrelated_histories"
  | "detached";

export type GitBackupStatus = Omit<
  GeneratedGitBackupStatus,
  "upstream_health"
> & {
  upstream_health: GitUpstreamHealth;
};

export type Project = Omit<ProjectDto, "workspace_type"> & {
  workspace_type: "project" | "linked";
};

export type ProjectSkill = Omit<ProjectSkillInfo_Serialize, "sync_status"> & {
  sync_status:
    | "project_only"
    | "in_sync"
    | "project_newer"
    | "center_newer"
    | "diverged";
};

export type GithubDevicePollResult = Omit<
  GeneratedGithubDevicePollResult,
  "status"
> & {
  status: "pending" | "slow_down" | "connected";
};

export type MergeSummary = Omit<GeneratedMergeSummary, "engine"> & {
  engine: "object" | "system";
};

export type SyncOutcome = Omit<GeneratedSyncOutcome, "merge"> & {
  merge: MergeSummary | null;
};

/** Actions accepted by `git_backup_resolve_conflict` (parsed from a string). */
export type ResolveConflictAction = "keep_local" | "use_remote" | "keep_both";

// ── Tools ──

export const getToolStatus = () => commands.getToolStatus();

export const setToolEnabled = (key: string, enabled: boolean) =>
  commands.setToolEnabled(key, enabled);

export const setAllToolsEnabled = (enabled: boolean) =>
  commands.setAllToolsEnabled(enabled);

export const getToolOrder = () => commands.getToolOrderCmd();

export const setToolOrder = (order: string[]) =>
  commands.setToolOrderCmd(order);

export const setCustomToolPath = (key: string, path: string) =>
  commands.setCustomToolPath(key, path);

export const resetCustomToolPath = (key: string) =>
  commands.resetCustomToolPath(key);

export const setCustomToolProjectPath = (
  key: string,
  projectRelativeSkillsDir: string | null,
) => commands.setCustomToolProjectPath(key, projectRelativeSkillsDir);

export const resetCustomToolProjectPath = (key: string) =>
  commands.resetCustomToolProjectPath(key);

export const addCustomTool = (
  key: string,
  displayName: string,
  skillsDir: string,
  projectRelativeSkillsDir?: string,
) =>
  commands.addCustomTool(
    key,
    displayName,
    skillsDir,
    projectRelativeSkillsDir ?? null,
  );

export const removeCustomTool = (key: string) =>
  commands.removeCustomTool(key);

// ── Skills ──

export const getManagedSkills = () => commands.getManagedSkills();

export const getSkillsForPreset = (presetId: string) =>
  commands.getSkillsForPreset(presetId);

export const getSkillDocument = (skillId: string) =>
  commands.getSkillDocument(skillId);

export const getSourceSkillDocument = (skillId: string) =>
  commands.getSourceSkillDocument(skillId);

export const getSkillSourceDiff = (skillId: string) =>
  commands.getSkillSourceDiff(skillId) as Promise<SkillSourceDiff>;

export const deleteManagedSkill = (skillId: string) =>
  commands.deleteManagedSkill(skillId);

export const deleteManagedSkills = (skillIds: string[]) =>
  commands.deleteManagedSkills(skillIds);

export const installLocal = (sourcePath: string, name?: string) =>
  commands.installLocal(sourcePath, name || null);

export const installGit = (repoUrl: string, name?: string) =>
  commands.installGit(repoUrl, name || null);

export const previewGitInstall = (repoUrl: string) =>
  commands.previewGitInstall(repoUrl);

export const confirmGitInstall = (
  repoUrl: string,
  tempDir: string,
  items: SkillInstallItem[],
) => commands.confirmGitInstall(repoUrl, tempDir, items);

export const cancelGitPreview = (tempDir: string) =>
  commands.cancelGitPreview(tempDir);

export const installFromSkillssh = (source: string, skillId: string) =>
  commands.installFromSkillssh(source, skillId);

export const cancelInstall = (key: string) => commands.cancelInstall(key);

export const checkSkillUpdate = (skillId: string, force?: boolean) =>
  commands.checkSkillUpdate(skillId, force ?? false);

export const checkAllSkillUpdates = (force?: boolean) =>
  commands.checkAllSkillUpdates(force ?? false);

/** `approvedRemovals` carries back `removal_approval` from a declined call. */
export const updateSkill = (skillId: string, approvedRemovals?: string | null) =>
  commands.updateSkill(skillId, approvedRemovals ?? null);

export const batchUpdateSkills = (skillIds: string[]) =>
  commands.batchUpdateSkills(skillIds);

export const reimportLocalSkill = (
  skillId: string,
  approvedRemovals?: string | null,
) => commands.reimportLocalSkill(skillId, approvedRemovals ?? null);

export const relinkLocalSkillSource = (
  skillId: string,
  sourcePath: string,
  approvedRemovals?: string | null,
) => commands.relinkLocalSkillSource(skillId, sourcePath, approvedRemovals ?? null);

export const detachLocalSkillSource = (skillId: string) =>
  commands.detachLocalSkillSource(skillId);

export const batchImportFolder = (folderPath: string) =>
  commands.batchImportFolder(folderPath);

export const getAllTags = () => commands.getAllTags();

export const setSkillTags = (skillId: string, tags: string[]) =>
  commands.setSkillTags(skillId, tags);

export const renameTag = (oldName: string, newName: string) =>
  commands.renameTag(oldName, newName);

export const deleteTag = (name: string) => commands.deleteTag(name);

// ── Sync ──

export const syncSkillToTool = (skillId: string, tool: string) =>
  commands.syncSkillToTool(skillId, tool);

export const unsyncSkillFromTool = (skillId: string, tool: string) =>
  commands.unsyncSkillFromTool(skillId, tool);

export const getSkillToolToggles = (skillId: string, presetId: string) =>
  commands.getSkillToolToggles(skillId, presetId);

export const setSkillToolToggle = (
  skillId: string,
  presetId: string,
  tool: string,
  enabled: boolean,
) => commands.setSkillToolToggle(skillId, presetId, tool, enabled);

// ── Scan ──

export const scanLocalSkills = () => commands.scanLocalSkills();

export const importExistingSkill = (sourcePath: string, name?: string) =>
  commands.importExistingSkill(sourcePath, name || null);

export const importAllDiscovered = () => commands.importAllDiscovered();

// ── Browse ──

export const fetchLeaderboard = (board: string) =>
  commands.fetchLeaderboard(board);

export const searchSkillssh = (query: string, limit?: number) =>
  commands.searchSkillssh(query, limit ?? null);

// ── Settings ──

export const getSettings = (key: string) => commands.getSettings(key);

export const setSettings = (key: string, value: string) =>
  commands.setSettings(key, value);

export const getCentralRepoPath = () => commands.getCentralRepoPath();

export const getCentralRepoPathOverride = () =>
  commands.getCentralRepoPathOverride();

export const getCentralRepoWarnings = () => commands.getCentralRepoWarnings();

export const setCentralRepoPath = (path?: string | null) =>
  commands.setCentralRepoPath(path ?? null);

export const appExit = () => commands.appExit();

export const hideToTray = () => commands.hideToTray();

export const openCentralRepoFolder = () => commands.openCentralRepoFolder();

export const checkAppUpdate = () => commands.checkAppUpdate();

/** Non-null when the app runs from somewhere an in-app update cannot be applied. */
export const updateInstallBlocker = () => commands.updateInstallBlocker();

export const restartApp = () => commands.restartApp();

export const getDiagnosticInfo = () => commands.getDiagnosticInfo();

export const getRecentLogExcerpt = () => commands.getRecentLogExcerpt();

export const exportLogsZip = () => commands.exportLogsZip();

export const checkLastPanic = () => commands.checkLastPanic();

export const clearLastPanic = () => commands.clearLastPanic();

/**
 * Diagnostic-only: write a named startup event with elapsed ms (from
 * performance.timeOrigin) into the backend log file. Used to correlate
 * WebView2 boot and frontend boot timing with Rust-side startup logs
 * when debugging slow launches (see issue #153).
 */
export const logStartupEvent = (label: string, elapsedMs: number) =>
  commands.logStartupEvent(label, Math.round(elapsedMs));

// ── Git Backup ──

export const gitBackupStatus = () =>
  commands.gitBackupStatus() as Promise<GitBackupStatus>;

export const gitBackupFetch = () => commands.gitBackupFetch();

export const gitBackupInit = () => commands.gitBackupInit();

/** Returns the sanitized URL actually configured (credentials moved to the OS keychain). */
export const gitBackupSetRemote = (url: string) =>
  commands.gitBackupSetRemote(url);

/** Strip embedded credentials into the OS keychain; returns the URL safe to persist. */
export const gitBackupSanitizeRemoteUrl = (url: string) =>
  commands.gitBackupSanitizeRemoteUrl(url);

/** GitHub guided connect (PAT): validates the token, finds or creates the
 * private backup repo, stores the token in the OS keychain, saves the URL. */
export const githubBackupConnect = (token: string, repoName: string) =>
  commands.githubBackupConnect(token, repoName);

export const githubDeviceFlowStart = () => commands.githubDeviceFlowStart();

/** One poll; on authorization the backend completes the whole connect and the
 * OAuth token never reaches the webview. */
export const githubDeviceFlowPoll = (deviceCode: string, repoName: string) =>
  commands.githubDeviceFlowPoll(deviceCode, repoName) as Promise<GithubDevicePollResult>;

/** Migrate token-in-URL remotes to the OS keychain. Returns the sanitized URL if migrated. */
export const gitBackupMigrateCredentials = () =>
  commands.gitBackupMigrateCredentials();

export const gitBackupSizeReport = () => commands.gitBackupSizeReport();

/** This machine's device name (§4.3): saved setting or persisted hostname default. */
export const backupDeviceName = () => commands.backupDeviceName();

/** Rename this device; only affects future backups. Returns the sanitized name. */
export const backupSetDeviceName = (name: string) =>
  commands.backupSetDeviceName(name);

export const gitBackupRemoveRemote = () => commands.gitBackupRemoveRemote();

export const gitBackupCommit = (message: string) =>
  commands.gitBackupCommit(message);

export const gitBackupPush = () => commands.gitBackupPush();

export const gitBackupPull = () =>
  commands.gitBackupPull() as Promise<MergeSummary>;

/** Outcome of the one-transaction sync (commit → merge → snapshot → push,
 * with automatic retry when another device pushes concurrently). */
export const gitBackupSync = (message: string) =>
  commands.gitBackupSync(message) as Promise<SyncOutcome>;

export const gitBackupPendingConflicts = () =>
  commands.gitBackupPendingConflicts();

/** Resolve a pending conflict; returns the safety snapshot tag. */
export const gitBackupResolveConflict = (
  skillId: string,
  action: ResolveConflictAction,
) => commands.gitBackupResolveConflict(skillId, action);

export const gitBackupClone = (url: string) => commands.gitBackupClone(url);

export const gitBackupReclone = (url: string) =>
  commands.gitBackupReclone(url);

export const gitBackupCreateSnapshot = () => commands.gitBackupCreateSnapshot();

export const gitBackupListVersions = (limit?: number) =>
  commands.gitBackupListVersions(typeof limit === "number" ? limit : null);

/** Returns the safety-point tag that captured the pre-restore state. */
export const gitBackupRestoreVersion = (tag: string) =>
  commands.gitBackupRestoreVersion(tag);

// ── Presets ──

export const getPresets = () => commands.getPresets();

export const getActivePreset = () => commands.getActivePreset();

export const createPreset = (name: string, description?: string, icon?: string) =>
  commands.createPreset(name, description || null, icon || null);

export const updatePreset = (
  id: string,
  name: string,
  description?: string,
  icon?: string,
) => commands.updatePreset(id, name, description || null, icon || null);

export const deletePreset = (id: string) => commands.deletePreset(id);

/** @deprecated v1.16+: clicking a scene no longer applies. Use applyPresetToDefault. */
export const switchPreset = (id: string) => commands.switchPreset(id);

export const applyPresetToDefault = (id: string) =>
  commands.applyPresetToDefault(id);

export const addSkillToPreset = (skillId: string, presetId: string) =>
  commands.addSkillToPreset(skillId, presetId);

export const removeSkillFromPreset = (skillId: string, presetId: string) =>
  commands.removeSkillFromPreset(skillId, presetId);

export const reorderPresets = (ids: string[]) => commands.reorderPresets(ids);

export const reorderProjects = (ids: string[]) => commands.reorderProjects(ids);

export const getPresetSkillOrder = (presetId: string) =>
  commands.getPresetSkillOrder(presetId);

export const reorderPresetSkills = (presetId: string, skillIds: string[]) =>
  commands.reorderPresetSkills(presetId, skillIds);

// ── Projects ──

export const getProjects = () => commands.getProjects() as Promise<Project[]>;

export const addProject = (path: string) =>
  commands.addProject(path) as Promise<Project>;

export const addLinkedWorkspace = (
  name: string,
  path: string,
  disabledPath?: string,
) =>
  commands.addLinkedWorkspace(name, path, disabledPath ?? null) as Promise<Project>;

export const removeProject = (id: string) => commands.removeProject(id);

export const scanProjects = (root: string) => commands.scanProjects(root);

export const getProjectAgentTargets = (projectId: string) =>
  commands.getProjectAgentTargets(projectId);

export const getProjectSkills = (projectId: string) =>
  commands.getProjectSkills(projectId) as Promise<ProjectSkill[]>;

export const getProjectSkillDocument = (
  projectId: string,
  skillRelativePath: string,
  agent: string,
) => commands.getProjectSkillDocument(projectId, skillRelativePath, agent);

export const importProjectSkillToCenter = (
  projectId: string,
  skillRelativePath: string,
  agent: string,
) => commands.importProjectSkillToCenter(projectId, skillRelativePath, agent);

export const exportSkillToProject = (
  skillId: string,
  projectId: string,
  agents?: string[],
) => commands.exportSkillToProject(skillId, projectId, agents ?? null);

export const updateProjectSkillToCenter = (
  projectId: string,
  skillRelativePath: string,
  agent: string,
) => commands.updateProjectSkillToCenter(projectId, skillRelativePath, agent);

export const updateProjectSkillFromCenter = (
  projectId: string,
  skillRelativePath: string,
  agent: string,
) => commands.updateProjectSkillFromCenter(projectId, skillRelativePath, agent);

export const toggleProjectSkill = (
  projectId: string,
  skillRelativePath: string,
  agent: string,
  enabled: boolean,
) => commands.toggleProjectSkill(projectId, skillRelativePath, agent, enabled);

export const deleteProjectSkill = (
  projectId: string,
  skillRelativePath: string,
  agent: string,
) => commands.deleteProjectSkill(projectId, skillRelativePath, agent);

export const slugifySkillNames = (names: string[]) =>
  commands.slugifySkillNames(names);

// ── Agent Local Workspace ──

export const getGlobalLocalSkills = (agent: string) =>
  commands.getGlobalLocalSkills(agent) as Promise<ProjectSkill[]>;

export const getGlobalLocalSkillDocument = (
  agent: string,
  skillRelativePath: string,
) => commands.getGlobalLocalSkillDocument(agent, skillRelativePath);

export const importGlobalLocalSkillToCenter = (
  agent: string,
  skillRelativePath: string,
) => commands.importGlobalLocalSkillToCenter(agent, skillRelativePath);

export const updateGlobalLocalSkillFromCenter = (
  agent: string,
  skillRelativePath: string,
) => commands.updateGlobalLocalSkillFromCenter(agent, skillRelativePath);

export const deleteGlobalLocalSkill = (
  agent: string,
  skillRelativePath: string,
) => commands.deleteGlobalLocalSkill(agent, skillRelativePath);
